/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */
import org.gradle.api.tasks.JavaExec

plugins {
    id("java")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.microsoft.sqlserver:mssql-jdbc:12.4.2.jre8")
    implementation("javax.mail:javax.mail-api:1.6.2")
    implementation("com.sun.mail:javax.mail:1.6.2")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.isIncremental = true
}

tasks.register<JavaExec>("run") {
    mainClass.set("terrenia.Main")
    classpath = sourceSets.main.get().runtimeClasspath
}

